BEGIN;

-- Rename challenges to old_challenges before generating from code first db app
ALTER TABLE challenges RENAME TO challenges_old;

-- Generate schema
create table challenges (id integer generated by default as identity, challenge varchar(255) not null unique, primary key (id));
create table challenges_instances (challenge_id integer not null, completed boolean not null, id integer generated by default as identity, completed_at timestamp(6), notes varchar(255), primary key (id), constraint check_is_completed_completed_at check ((completed = false AND completed_at IS NULL) OR (completed = true AND completed_at IS NOT NULL)));
create table difficulties (id integer generated by default as identity, difficulty varchar(255) not null unique, primary key (id));
create table heists (id integer generated by default as identity, name varchar(255) not null unique, primary key (id));
create table heists_completed (accurate_xp_input boolean not null, all_bags_secured boolean not null, difficulty SMALLINT not null, heist SMALLINT not null, heist_finish_state SMALLINT not null check ((heist_finish_state in (0,1,2,3,4,5,6,7))), heist_success boolean not null, id integer generated by default as identity, xp_amount integer not null, completed_at TIMESTAMP(3) not null, notes varchar(255), primary key (id));
alter table if exists challenges_instances add constraint FKcjql3oblbel27i3knt6fcpsmv foreign key (challenge_id) references challenges;
alter table if exists heists_completed add constraint FKqc8byw709o0dwf50if9arlh30 foreign key (difficulty) references difficulties;
alter table if exists heists_completed add constraint FK14eo6q6t93tplxmiafkwa54m5 foreign key (heist) references heists;



COMMIT;