package dev.centremetre.paydaylog.dto;

import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

/**
 * DTO for {@link dev.centremetre.paydaylog.model.CompletedHeist}
 * Generated by JPABuddy
 */
public class CompletedHeistCreateDto // implements Serializable // Serialisable not needed
{

    // @NotNull no needed on primitives.
    // TODO: Change to not use primitives,but Integer and Boolean for better error message returning.
    private int xpAmount;
    private boolean isAccurateXpInput;
    /**
     * ID used since that should be sent by client, to reduce size.
     */
    private int heistId;
    @NotNull
    private LocalDateTime completedAt;
    private boolean heistSuccess;
    /**
     * ID used since that should be sent by client, to reduce size.
     */
    private int heistFinishStateId;
    private boolean allBagsSecured;
    /**
     * ID used since that should be sent by client, to reduce size.
     */
    private int difficultyId;
    private String notes;

    public int getXpAmount()
    {
        return xpAmount;
    }

    public void setXpAmount(int xpAmount)
    {
        this.xpAmount = xpAmount;
    }

    public boolean getIsAccurateXpInput()
    {
        return isAccurateXpInput;
    }

    public void setIsAccurateXpInput(boolean isAccurateXpInput)
    {
        this.isAccurateXpInput = isAccurateXpInput;
    }

    public int getHeistId()
    {
        return heistId;
    }

    public void setHeistId(int heistId)
    {
        this.heistId = heistId;
    }

    public LocalDateTime getCompletedAt()
    {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt)
    {
        this.completedAt = completedAt;
    }

    public boolean getHeistSuccess()
    {
        return heistSuccess;
    }

    public void setHeistSuccess(boolean heistSuccess)
    {
        this.heistSuccess = heistSuccess;
    }

    public int getHeistFinishStateId()
    {
        return heistFinishStateId;
    }

    public void setHeistFinishStateId(int heistFinishStateId)
    {
        this.heistFinishStateId = heistFinishStateId;
    }

    public boolean getIsMajorityStatePlayedStealth()
    {
        return allBagsSecured;
    }

    public void setIsMajorityStatePlayedStealth(boolean isMajorityStatePlayedStealth)
    {
        this.allBagsSecured = isMajorityStatePlayedStealth;
    }

    public int getDifficultyId()
    {
        return difficultyId;
    }

    public void setDifficultyId(int difficultyId)
    {
        this.difficultyId = difficultyId;
    }

    public String getNotes()
    {
        return notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }
}