package dev.centremetre.paydaylog.dto;

import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * DTO for {@link dev.centremetre.paydaylog.model.CompletedHeist}
 * Generated by JPABuddy
 */
public class CompletedHeistReturnDto // implements Serializable // Serialisable not needed
{
    private int id;
    private int xpAmount;
    private boolean isAccurateXpInput;
    private String heistName;
    @NotNull
    private LocalDateTime completedAt;
    private boolean heistSuccess;
    private int heistFinishState;
    private boolean isMajorityStatePlayedStealth;
    private String difficultyDifficulty;
    private String notes;

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public int getXpAmount()
    {
        return xpAmount;
    }

    public void setXpAmount(int xpAmount)
    {
        this.xpAmount = xpAmount;
    }

    public boolean getIsAccurateXpInput()
    {
        return isAccurateXpInput;
    }

    public void setIsAccurateXpInput(boolean isAccurateXpInput)
    {
        this.isAccurateXpInput = isAccurateXpInput;
    }

    public String getHeistName()
    {
        return heistName;
    }

    public void setHeistName(String heistName)
    {
        this.heistName = heistName;
    }

    public LocalDateTime getCompletedAt()
    {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt)
    {
        this.completedAt = completedAt;
    }

    public boolean getHeistSuccess()
    {
        return heistSuccess;
    }

    public void setHeistSuccess(boolean heistSuccess)
    {
        this.heistSuccess = heistSuccess;
    }

    public int getHeistFinishState()
    {
        return heistFinishState;
    }

    public void setHeistFinishState(int heistFinishState)
    {
        this.heistFinishState = heistFinishState;
    }

    public boolean getIsMajorityStatePlayedStealth()
    {
        return isMajorityStatePlayedStealth;
    }

    public void setIsMajorityStatePlayedStealth(boolean isMajorityStatePlayedStealth)
    {
        this.isMajorityStatePlayedStealth = isMajorityStatePlayedStealth;
    }

    public String getDifficultyDifficulty()
    {
        return difficultyDifficulty;
    }

    public void setDifficultyDifficulty(String difficultyDifficulty)
    {
        this.difficultyDifficulty = difficultyDifficulty;
    }

    public String getNotes()
    {
        return notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }
}