package dev.centremetre.paydaylog.dto;

import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

/**
 * DTO for {@link dev.centremetre.paydaylog.model.CompletedHeist}
 * Generated by JPABuddy
 */
public class CompletedHeistCreateDto // implements Serializable // Serialisable not needed
{
    private int xpAmount;
    private boolean isAccurateXpInput;
    private int heistId;
    @NotNull
    private LocalDateTime completedAt;
    private boolean heistSuccess;
    private int heistFinishState;
    private boolean isMajorityStatePlayedStealth;
    private int difficultyId;
    private String notes;

    public int getXpAmount()
    {
        return xpAmount;
    }

    public void setXpAmount(int xpAmount)
    {
        this.xpAmount = xpAmount;
    }

    public boolean getIsAccurateXpInput()
    {
        return isAccurateXpInput;
    }

    public void setIsAccurateXpInput(boolean isAccurateXpInput)
    {
        this.isAccurateXpInput = isAccurateXpInput;
    }

    public int getHeistId()
    {
        return heistId;
    }

    public void setHeistId(int heistId)
    {
        this.heistId = heistId;
    }

    public LocalDateTime getCompletedAt()
    {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt)
    {
        this.completedAt = completedAt;
    }

    public boolean getHeistSuccess()
    {
        return heistSuccess;
    }

    public void setHeistSuccess(boolean heistSuccess)
    {
        this.heistSuccess = heistSuccess;
    }

    public int getHeistFinishState()
    {
        return heistFinishState;
    }

    public void setHeistFinishState(int heistFinishState)
    {
        this.heistFinishState = heistFinishState;
    }

    public boolean getIsMajorityStatePlayedStealth()
    {
        return isMajorityStatePlayedStealth;
    }

    public void setIsMajorityStatePlayedStealth(boolean isMajorityStatePlayedStealth)
    {
        this.isMajorityStatePlayedStealth = isMajorityStatePlayedStealth;
    }

    public int getDifficultyId()
    {
        return difficultyId;
    }

    public void setDifficultyId(int difficultyId)
    {
        this.difficultyId = difficultyId;
    }

    public String getNotes()
    {
        return notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }
}